[web]
  title = "Redwood App"
  port = 8910
  apiUrl = "/api"
  includeEnvironmentVariables = [ "SUPABASE_URL", "SUPABASE_KEY"]
[api]
  port = 8911
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
